---
title: "EM2_databehandling"
output: pdf_document
date: "2025-12-03"
---

```{r setup, include=FALSE}
library("rstatix")
library("psych")
library("tidyverse")
library("BayesFactor")
library("dplyr")
library("lme4")
library("lmerTest")
library("effects")
library("emmeans")
```

## Pre-processing of data

```{r}

# get list of data files in current directory (excluding questionnaire data)
list_of_files <- setdiff(dir(pattern=".csv"), "questionnaire.csv")

# create data frame
df <- read_delim(list_of_files) %>%
  mutate(ReactionTime = ReactionTime * 1000) 

# identify subjects to exclude
slow_subjects <- df %>%
  filter(Ball_present == TRUE) %>%
  group_by(subject_id) %>%
  summarise(RT_over_1000 = sum(ReactionTime > 1000, na.rm = TRUE)) %>%
  filter(RT_over_1000 > 4) %>%
  pull(subject_id)

error_subjects <- df %>%
  group_by(subject_id) %>%
  summarise(error_trials = sum(response == "missed" | 
              response == "false_alarm" |
              (X_Hit == "No" & response == "hit"))) %>%
  filter(error_trials > 8) %>%
  pull(subject_id)

# exclude subjects
df_new <- df %>%
  filter(!subject_id %in% slow_subjects, !subject_id %in% error_subjects)

# exclude trials (slow RTs and no X-hit)
df_ex <- df_new %>%
  filter(!(Ball_present == TRUE & response == "hit" & ReactionTime > 1000),
         X_Hit == "Yes") 

# create final data frame to use for analysis
df_final <- df_ex %>%
  filter(Ball_present == TRUE, response == "hit") %>% 
  group_by(subject_id) %>%
  mutate(Agent_First  = first(Agent_Type),
         Agent_Second = if_else(Agent_First == "Self", "Smurf", "Self")
         ) %>%
  ungroup()
  
```
## Pre-processing of questionnaire data

```{r}

# create questionnaire data frame
quest <- read.csv("questionnaire.csv", sep=";")

# correct subject-id's to fit other data frame
quest$subject_id[quest$subject_id == 1] <- "0001"
quest$subject_id[quest$subject_id == 409] <- "0409"
quest$subject_id[quest$subject_id == 511] <- "0511"
quest$subject_id[quest$subject_id == 708] <- "0708"

# compute immersiveness scores
quest_scores <- quest %>%
  mutate(score_smurf = (
           Q1_smurf +
           Q2_smurf +
           Q3_smurf +
           Q4_smurf +
           Q5_smurf +
           Q6_smurf +
           Q7_smurf +
           Q8_smurf) / 8,
         score_self = (
           Q1_self +
           Q2_self +
           Q3_self +
           Q4_self +
           Q5_self +
           Q6_self +
           Q7_self +
           Q8_self) / 8
         )

# combine data frames
df_combined <- df_final %>%
  group_by(subject_id, Agent_Type, Condition, Agent_First) %>%
  summarise(meanRT = mean(ReactionTime, na.rm = TRUE)) %>%
  ungroup() %>%
  left_join(quest_scores %>% select(subject_id, score_smurf, score_self, Q1_self, Q8_self),
            by = "subject_id")
```

## Accuracy

```{r}

no_x_hit <- df_new %>%
  filter(X_Hit == "No")

slow_trials <- df_new %>%
  filter(Ball_present == TRUE & response == "hit" & ReactionTime > 1000)

ex_trials <- df_new %>%
  filter(X_Hit == "No" |
        (Ball_present == TRUE & response == "hit" & ReactionTime > 1000))

hits <- df_ex %>% 
  filter(response == "hit")

misses <- df_ex %>%
  filter(response == "missed")

false_alarms <- df_ex %>%
  filter(response == "false_alarm")

correct_rejections <- df_ex %>%
  filter(response == "no_press")

# calculate errors
errors <- nrow(false_alarms) + nrow(misses)

# calculate error percentage
(errors / nrow(df_ex)) * 100

# calculate false alarm percentage
(nrow(false_alarms) / nrow(df_ex)) * 100

# calculate miss percentage
(nrow(misses) / nrow(df_ex)) * 100

# no x hit percentage
nrow(no_x_hit) / nrow(df_new) * 100

# slow trials percentage
nrow(slow_trials) / nrow(df_new) * 100

# excluded trials percentage
nrow(ex_trials) / nrow(df_new) * 100

```

## RT plots

```{r}

# compute mean RTs for smurf trials
means_smurf <- df_combined %>% 
  filter(Agent_Type == "Smurf") %>% 
  group_by(Condition) %>% 
  summarise(meanRT_smurf = mean(meanRT, na.rm = TRUE),
            SD = sd(meanRT),
            N = n(),
            SE = SD / sqrt(N))

# compute mean RTs for self trials
means_self <- df_combined %>% 
  filter(Agent_Type == "Self") %>% 
  group_by(Condition) %>% 
  summarise(meanRT_self = mean(meanRT, na.rm = TRUE),
            SD = sd(meanRT),
            N = n(),
            SE = SD / sqrt(N))

# compute overall mean RTs
means_overall <- df_combined %>% 
  group_by(Condition) %>% 
  summarise(meanRT_overall = mean(meanRT, na.rm = TRUE),
            SD = sd(meanRT),
            N = n(),
            SE = SD / sqrt(N))

# change order of conditions in data frames
means_smurf$Condition <- factor(means_smurf$Condition, 
                                levels = c("P+A-","P-A+","P-A-","P+A+")) 

means_self$Condition <- factor(means_self$Condition, 
                               levels = c("P+A-","P-A+","P-A-","P+A+"))  

means_overall$Condition <- factor(means_self$Condition, 
                                  levels = c("P+A-","P-A+","P-A-","P+A+"))  

# plot mean RTs for smurf trials
ggplot(means_smurf, aes(x = meanRT_smurf, y = Condition)) +
  geom_col(fill = "#0096FF") +
  geom_errorbarh(aes(xmin = meanRT_smurf - SE, xmax = meanRT_smurf + SE),
                 height = 0.2, size = 0.4) +
  coord_cartesian(xlim = c(400, 560)) +
  scale_x_continuous(
    breaks = seq(400, 560, by = 10)
    ) +
  labs(title = "Mean Reaction Times (Smurf)",
       x = "Mean reaction time (ms)",
       y = "Condition"
       ) +
  theme_grey(base_size = 12)

# plot mean RTs for self trials
ggplot(means_self, aes(x = meanRT_self, y = Condition)) +
  geom_col(fill = "#FF00FF") +
  geom_errorbarh(aes(xmin = meanRT_self - SE, xmax = meanRT_self + SE),
                 height = 0.2, size = 0.4) +
  coord_cartesian(xlim = c(400, 560)) +
  scale_x_continuous(
    breaks = seq(400, 560, by = 10)
    ) +
  labs(title = "Mean Reaction Times (Self)",
       x = "Mean reaction time (ms)",
       y = "Condition"
       ) +
  theme_grey(base_size = 12)

# plot overall mean RTs
ggplot(means_overall, aes(x = meanRT_overall, y = Condition)) +
  geom_col(fill = "grey") +
  geom_errorbarh(aes(xmin = meanRT_overall - SE, xmax = meanRT_overall + SE),
                 height = 0.2, size = 0.4) +
  coord_cartesian(xlim = c(400, 560)) +
  scale_x_continuous(
    breaks = seq(400, 560, by = 10)
    ) +
  labs(title = "Mean Reaction Times (Overall)",
       x = "Mean reaction time (ms)",
       y = "Condition"
       ) +
  theme_grey(base_size = 12)

```

## T-tests for ToM-effect

```{r}

# transform to wide format
df_wide <- df_combined %>%
  pivot_wider(
    names_from = Condition,
    values_from = meanRT
  ) %>%
  mutate(mean_diff = `P-A-` - `P-A+`)

# filter self trials
df_self_wide <- df_wide %>%
  filter(Agent_Type == "Self")

# filter smurf trials
df_smurf_wide <- df_wide %>%
  filter(Agent_Type == "Smurf")

# self ToM-effect 
ttestBF(df_self_wide$`P-A+`, df_self_wide$`P-A-`, paired = TRUE)

# smurf ToM-effect
ttestBF(df_smurf_wide$`P-A+`, df_smurf_wide$`P-A-`, paired = TRUE)

# overall ToM-effect
ttestBF(df_wide$`P-A+`, df_wide$`P-A-`, paired = TRUE)

# difference between self and smurf in ToM-effect
ttestBF(df_self_wide$mean_diff, df_smurf_wide$mean_diff, paired = TRUE)

```

## Block order effects

```{r}

# filter by block order
df_self_first <- df_wide %>%
  filter(Agent_First == "Self")

df_smurf_first <- df_wide %>%
  filter(Agent_First == "Smurf")

# filter by block order and agent type
df_self_first_self <- df_self_first %>%
  filter(Agent_Type == "Self")

df_self_first_smurf <- df_self_first %>%
  filter(Agent_Type == "Smurf")

df_smurf_first_smurf <- df_smurf_first %>%
  filter(Agent_Type == "Smurf")

df_smurf_first_self <- df_smurf_first %>%
  filter(Agent_First == "Smurf")

# self first ToM-effect (only self trials)
ttestBF(df_self_first_self$`P-A+`, df_self_first_self$`P-A-`, paired = TRUE)

# self first ToM-effect (all trials)
ttestBF(df_self_first$`P-A+`, df_self_first$`P-A-`, paired = TRUE)


```

## Blockwise RT plots

```{r}

# compute mean RTs for self trials (when self is first)
means_self_first_self <- df_combined %>% 
  filter(Agent_First == "Self", Agent_Type == "Self") %>% 
  group_by(Condition) %>% 
  summarise(meanRT_self = mean(meanRT, na.rm = TRUE),
            SD = sd(meanRT),
            N = n(),
            SE = SD / sqrt(N))

# compute mean RTs for smurf trials (when self is first)
means_self_first_smurf <- df_combined %>% 
  filter(Agent_First == "Self", Agent_Type == "Smurf") %>% 
  group_by(Condition) %>% 
  summarise(meanRT_smurf = mean(meanRT, na.rm = TRUE),
            SD = sd(meanRT),
            N = n(),
            SE = SD / sqrt(N))

# compute mean RTs for self trials (when smurf is first)
means_smurf_first_self <- df_combined %>% 
  filter(Agent_First == "Smurf", Agent_Type == "Self") %>% 
  group_by(Condition) %>% 
  summarise(meanRT_self = mean(meanRT, na.rm = TRUE),
            SD = sd(meanRT),
            N = n(),
            SE = SD / sqrt(N))

# compute mean RTs for self trials (when smurf is first)
means_smurf_first_smurf <- df_combined %>% 
  filter(Agent_First == "Smurf", Agent_Type == "Smurf") %>% 
  group_by(Condition) %>% 
  summarise(meanRT_smurf = mean(meanRT, na.rm = TRUE),
            SD = sd(meanRT),
            N = n(),
            SE = SD / sqrt(N))


# change order of conditions in data frame
means_self_first_self$Condition <- factor(means_self$Condition,
                                          levels = c("P+A-","P-A+","P-A-","P+A+"))  

means_self_first_smurf$Condition <- factor(means_self$Condition,
                                          levels = c("P+A-","P-A+","P-A-","P+A+"))

means_smurf_first_self$Condition <- factor(means_self$Condition,
                                          levels = c("P+A-","P-A+","P-A-","P+A+"))

means_smurf_first_smurf$Condition <- factor(means_self$Condition,
                                          levels = c("P+A-","P-A+","P-A-","P+A+"))

# plot mean RTs for self in first block
ggplot(means_self_first_self, aes(x = meanRT_self, y = Condition)) +
  geom_col(fill = "#FF00FF") +
  geom_errorbarh(aes(xmin = meanRT_self - SE, xmax = meanRT_self + SE),
                 height = 0.2, size = 0.4) +
  coord_cartesian(xlim = c(400, 590)) +
  scale_x_continuous(
    breaks = seq(400, 590, by = 10)
    ) +
  labs(title = "Mean Reaction Times (Self First)",
       x = "Mean reaction time (ms)",
       y = "Condition"
       ) +
  theme_grey(base_size = 12)

# plot mean RTs for smurf in second block
ggplot(means_self_first_smurf, aes(x = meanRT_smurf, y = Condition)) +
  geom_col(fill = "#0096FF") +
  geom_errorbarh(aes(xmin = meanRT_smurf - SE, xmax = meanRT_smurf + SE),
                 height = 0.2, size = 0.4) +
  coord_cartesian(xlim = c(400, 590)) +
  scale_x_continuous(
    breaks = seq(400, 590, by = 10)
    ) +
  labs(title = "Mean Reaction Times (Smurf Second)",
       x = "Mean reaction time (ms)",
       y = "Condition"
       ) +
  theme_grey(base_size = 12)

# plot mean RTs for smurf in first block
ggplot(means_smurf_first_smurf, aes(x = meanRT_smurf, y = Condition)) +
  geom_col(fill = "#0096FF") +
  geom_errorbarh(aes(xmin = meanRT_smurf - SE, xmax = meanRT_smurf + SE),
                 height = 0.2, size = 0.4) +
  coord_cartesian(xlim = c(400, 590)) +
  scale_x_continuous(
    breaks = seq(400, 590, by = 10)
    ) +
  labs(title = "Mean Reaction Times (Smurf First)",
       x = "Mean reaction time (ms)",
       y = "Condition"
       ) +
  theme_grey(base_size = 12)

# plot mean RTs for self in second block
ggplot(means_smurf_first_self, aes(x = meanRT_self, y = Condition)) +
  geom_col(fill = "#FF00FF") +
  geom_errorbarh(aes(xmin = meanRT_self - SE, xmax = meanRT_self + SE),
                 height = 0.2, size = 0.4) +
  coord_cartesian(xlim = c(400, 590)) +
  scale_x_continuous(
    breaks = seq(400, 590, by = 10)
    ) +
  labs(title = "Mean Reaction Times (Self Second)",
       x = "Mean reaction time (ms)",
       y = "Condition"
       ) +
  theme_grey(base_size = 12)

```

## Compute means

```{r}

meanRT_smurf <- mean(means_smurf$meanRT_smurf)

meanRT_self <- mean(means_self$meanRT_self)

meanRT_overall <- mean(means_overall$meanRT_overall)

mean_diff_smurf <- mean(df_smurf_wide$mean_diff)

mean_diff_self <- mean(df_self_wide$mean_diff)

mean_diff_self_first <- mean(df_self_first_self$mean_diff)

# count self first and smurf first participants
df_combined %>%
  distinct(subject_id, Agent_First) %>%
  count(Agent_First)

  
```


## Questionnaire correlations

```{r}

# filter out missing data
df_self_wide_filt <- df_self_wide %>%
  filter(subject_id != 1738)

df_smurf_wide_filt <- df_self_wide %>%
  filter(subject_id != 1738)

# correlation test self
correlationBF(df_self_wide_filt$score_self, df_self_wide_filt$mean_diff)

ggplot(df_self_wide_filt, aes(x = score_self, y = mean_diff)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_minimal() +
  labs(x = "Immersiveness score", y = "ToM-index",
       title = "Correlation Plot (Self)")

# correlation test smurf
correlationBF(df_smurf_wide_filt$score_smurf, df_smurf_wide_filt$mean_diff)

ggplot(df_smurf_wide_filt, aes(x = score_smurf, y = mean_diff)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_minimal() +
  labs(x = "Immersiveness score", y = "ToM-index",
       title = "Correlation Plot (Smurf)")

# correlation between similarity (Q1) and ToM-index in self trials
correlationBF(df_self_wide_filt$Q1_self, df_self_wide_filt$mean_diff)

ggplot(df_self_wide_filt, aes(x = Q1_self, y = mean_diff)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_minimal() +
  labs(x = "Q1", y = "ToM-index",
       title = "Correlation Plot (Similarity)")

# correlation test self first self
df_self_first_self_filt <- df_self_first_self %>%
  filter(subject_id != 1738)

correlationBF(df_self_first_self_filt$score_self, df_self_first_self_filt$mean_diff)

ggplot(df_self_first_self_filt, aes(x = score_self, y = mean_diff)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_minimal() +
  labs(x = "Immersiveness score", y = "ToM-index",
       title = "Correlation Plot (Self First, Self)")

```


## Questionnaire means

```{r}

# filter out missing data
quest_scores_filt <- quest_scores %>%
  filter(subject_id != 1738)

# calculate mean scores
mean(quest_scores_filt$score_self)
mean(quest_scores_filt$score_smurf)

ttestBF(quest_scores_filt$score_self, quest_scores_filt$score_smurf, paired = TRUE)

# mean Q8 score
mean(quest_scores_filt$Q8_self)
mean(quest_scores_filt$Q8_smurf)

# mean Q1 score
mean(quest_scores_filt$Q1_smurf)
mean(quest_scores_filt$Q1_self)

# mean perspective taking scores
(mean(quest_scores_filt$Q8_self) + mean(quest_scores_filt$Q7_self) + mean(quest_scores_filt$Q6_self)) / 3

(mean(quest_scores_filt$Q8_smurf) + mean(quest_scores_filt$Q7_smurf) + mean(quest_scores_filt$Q6_smurf)) / 3

```

## Linear mixed model

```{r}

# all factors
model <- lmer(
  meanRT ~ Condition * Agent_First * Agent_Type + (1 | subject_id),
  data = df_combined %>% filter(Condition %in% c('P-A-','P-A+'))
  )

summary(model)

plot(allEffects(model))

emm_agent <- emmeans(model, ~ Agent_Type)
emm_agent

contrast(emm_agent, method = "pairwise")

```


```{r}

model2 <- lmer(
  mean_diff ~ Agent_Type * Agent_First + (1 | subject_id),
  data = df_wide
  )

summary(model2)

plot(allEffects(model2))

```

```{r}

# participant belief
model3 <- lmer(
  ReactionTime ~ Part_belief + (1 | subject_id),
  data = df_final %>% filter(Agent_First == "Smurf")
  )

summary(model3)

plot(allEffects(model3))

```


```{r}

# agent belief
model4 <- lmer(
  ReactionTime ~ Agent_belief + (1 | subject_id),
  data = df_final # %>% filter(Agent_First == "Self", Agent_Type == "Self")
  )

summary(model4)

plot(allEffects(model4))

```

